{"name": "test_login[login_username_error]", "status": "passed", "attachments": [{"name": "log", "source": "0d0c05e8-67f1-44f8-ba14-184da0a2cbe0-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'case': 'login_username_error', 'username': 18538231110, 'password': 'Gold77899', 'expected': '用户账户或密码错误'}"}], "start": 1756525591569, "stop": 1756525596200, "uuid": "c3f2b0de-074f-49fc-8dbb-1f47f84029e6", "historyId": "3ca944dea214f69b3bc91f5301606c9c", "testCaseId": "c54ba4c514553f220eeed2f7e798b554", "fullName": "testcase.test_login.TestLogin#test_login", "labels": [{"name": "story", "value": "用户登录"}, {"name": "feature", "value": "用户登录"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "li"}, {"name": "thread", "value": "10064-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}], "titlePath": ["testcase", "test_login.py", "TestLogin"]}