{"name": "test_login[login_password_error]", "status": "passed", "attachments": [{"name": "log", "source": "3378776a-e099-4376-8791-13832d277e4d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'case': 'login_password_error', 'username': 18538231111, 'password': 'Gold7789', 'expected': '密码错误'}"}], "start": 1756038568706, "stop": 1756038573134, "uuid": "9fcfc749-ec97-4ae5-94d8-febb75ebc76c", "historyId": "0cbb37dbacea741fda169ac537e8da69", "testCaseId": "c54ba4c514553f220eeed2f7e798b554", "fullName": "testcase.test_login.TestLogin#test_login", "labels": [{"name": "story", "value": "用户登录"}, {"name": "feature", "value": "用户登录"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "li"}, {"name": "thread", "value": "8652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}], "titlePath": ["testcase", "test_login.py", "TestLogin"]}